version: "3.7"
services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      TZ: Asia/Seoul
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--explicit_defaults_for_timestamp=1"]
    volumes:
      - mysql-data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: "10"

  redis:
    image: redis:alpine
    command: redis-server --requirepass root
    container_name: redis
    ports:
      - "6379:6379"
    labels:
      - "name=redis"
      - "mode=standalone"

  forum-server:
    depends_on:
      - db
      - redis
    image: test-server:1.0.0
    container_name: "server"
    environment:
      NODE_ENV: prod
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: db
      PRIVATE_KEY: KR_TEST
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: root
      REGION: kr
      PORT: 5050
      IS_TEST: "true"
    ports:
      - "5050:5050"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: "10"

volumes:
  mysql-data: {}

